config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip:[:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    root to: 'homes#top'
    resources :items, expect:[:destroy]
    resources :genres, only:[:index, :edit, :create, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
  end

  root to: "public/homes#top"

  devise_for :customer, skip:[:passwords], controllers:{
    registrations: "customer/registrations",
    sessions: "customer/sessions"
  }

  scope module: :public do
    get "/about", to: "homes#about"
    get "/customers/unsubscribe", to: "customers#unsubscribe"
    patch "/customers/withdraw", to: "customers#withdraw"
    resource :customers, only:[:show, :edit, :update]
    resources :items, only:[:index, :show]
    resources :cart_items, except:[:show, :new, :edit]
    delete "/cart_items", to: "cart_items#destroy_all"
    resources :orders, except:[:edit, :update, :destroy] do
      collection do
        get "complete"
        post "confirm"
      end
    end
    resources :deliveries, except:[:new, :show]

    get '/genre_search', to: "searches#genre_search"
    get '/item_search', to: "searches#item_search"
   end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items  , dependent: :destroy
  has_many :orders         , dependent: :destroy
  has_many :deliveries     , dependent: :destroy

  def full_name
   last_name + " " + first_name
  end

  def full_name_kana
    last_name_kana + " " + first_name_kana
  end

  def full_name_no_blanks
    last_name + first_name
  end

  def full_address
    "〒" + self.postal_code + "  " + self.address + last_name + " " + first_name
  end

  def cart_items_total_price
    sum = 0
    self.cart_items.each { |cart_item| sum += cart_item.sum_of_price }
    return sum
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  layout "admin"
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find([params[:id]])
    if customer.update(customer_params)
      redirect_to admins_customer_path(customer)
    else
      redirect_to request.referer
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :email, :is_deleted)
  end

end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    customers_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,
                                                       :first_name,
                                                       :last_name_kana,
                                                       :first_name_kana,
                                                       :postal_code,
                                                       :address,
                                                       :phone_number,
                                                      ])
  end

end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def customer_state
    @customer = Customer.find_by(email: params[:customer][:email])
    return if !@customer
    if (@customer.valid_password?(params[:customer][:password])) && (@customer.is_deleted == true)
      flash[:notice] = "このアカウントは退会済みです。新規登録を行ってください。"
      redirect_to new_customer_registration_path
    end
  end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h3 class="offset-1">
  <%= @customer.full_name_no_blanks %>さんの会員情報編集
</h3>

<div class="row ml-4 mt-3">
<%= form_with model: @customer, url: admin_customer_path(@customer), local: true do |f| %>
  <div class="form-group row">
    <div class="col-4">会員ID</div>
    <div class="col-8"><%= @customer.id %></div>
  </div>

  <div class="form-group row">
    <div class="col-4"><%= f.label :氏名 %></div>
    <div class="col-4"><%= f.text_field :last_name, class: "form-control" %></div>
    <div class="col-4"><%= f.text_field :first_name, class: "form-control" %></div>
  </div>

  <div class="form-group row">
    <div class="col-4"><%= f.label :フリガナ %></div>
    <div class="col-4"><%= f.text_field :last_name_kana, class: "form-control" %></div>
    <div class="col-4"><%= f.text_field :first_name_kana, class: "form-control" %></div>
  </div>

  <div class="form-group row">
    <div class="col-4"><%= f.label :郵便番号 %></div>
    <div class="col-8"><%= f.text_field :postal_code, class: "form-control" %></div>
  </div>

  <div class="form-group row">
    <div class="col-4"><%= f.label :住所 %></div>
    <div class="col-8"><%= f.text_field :address, class: "form-control" %></div>
  </div>

  <div class="form-group row">
    <div class="col-4"><%= f.label :電話番号 %></div>
    <div class="col-8"><%= f.text_field :phone_number, class: "form-control" %></div>
  </div>

  <div class="form-group row">
    <div class="col-4"><%= f.label :メールアドレス %></div>
    <div class="col-8"><%= f.email_field :email, class: "form-control" %></div>
  </div>

  <div class="form-group row">
    <div class="col-4"><%= f.label :会員ステータス %></div>
    <div class="col-8">
      <%= f.radio_button :is_deleted,false,checked:true %>
      <%= f.label :有効 %>
      <%= f.radio_button :is_deleted,true, class: "ml-3" %>
      <%= f.label :退会 %>
    </div>
  </div>

  <div class="row">
    <div class="col-4"></div>
    <div class="col-8"><%= f.submit "変更を保存", class: "btn btn-success" %></div>
  </div>
<% end %>
</div>

app/views/admin/customers/index.html.erb
<h3 class="offset-1">会員一覧</h3>

<div class="row offset-2 col-8 mt-3">
  <table class="table table-light table-striped">
    <thead>
      <tr class="text-white bg-dark">
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    
    <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= link_to customer.full_name_no_blanks, admin_customer_path(customer), class: "text-dark", style: "text-decoration: underline" %></td>
        <td><%= customer.email %></td>
        <td>
          <% if customer.is_deleted? %>
            <span class="text-secondary"><strong>退会</strong></span>
          <% else %>
            <span class="text-success"><strong>有効</strong></span>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/customers/show.html.erb
<h3 class="offset-1">
  <%= @customer.full_name_no_blanks %>さんの会員詳細
</h3>

<div class="col-6 ml-4">

  <div class="row mt-3">
    <div class="col-4">会員ID</div>
    <div class="col-8"><%= @customer.id %></div>
  </div>

  <div class="row mt-3">
    <div class="col-4">氏名</div>
    <div class="col-8"><%= @customer.full_name %></div>
  </div>

  <div class="row mt-3">
    <div class="col-4">フリガナ</div>
    <div class="col-8"><%= @customer.full_name_kana %></div>
  </div>

  <div class="row mt-3">
    <div class="col-4">郵便番号</div>
    <div class="col-8"><%= @customer.postal_code %></div>
  </div>

  <div class="row mt-3">
    <div class="col-4">住所</div>
    <div class="col-8"><%= @customer.address %></div>
  </div>

  <div class="row mt-3">
    <div class="col-4">電話番号</div>
    <div class="col-8"><%= @customer.phone_number %></div>
  </div>

  <div class="row mt-3">
    <div class="col-4">メールアドレス</div>
    <div class="col-8"><%= @customer.email %></div>
  </div>

  <div class="row mt-3">
    <div class="col-4">会員ステータス</div>
    <div class="col-8">
      <% if @customer.is_deleted? %>
        <div class="text-secondary"><strong>退会</strong></div>
      <% else %>
        <div class="text-success"><strong>有効</strong></div>
      <% end %>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-4"></div>
    <div class="col-3"><%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %></div>
    <div class="col-5"><%= link_to "注文履歴一覧を見る", admin_orders_path(customer_id: @customer), class: "btn btn-primary" %></div>
  </div>
</div>