config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip:[:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    root to: 'homes#top'
    resources :items, expect:[:destroy]
    resources :genres, only:[:index, :edit, :create, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
  end

  root to: "public/homes#top"

  devise_for :customer, skip:[:passwords], controllers:{
    registrations: "customer/registrations",
    sessions: "customer/sessions"
  }

  scope module: :public do
    get "/about", to: "homes#about"
    get "/customers/unsubscribe", to: "customers#unsubscribe"
    patch "/customers/withdraw", to: "customers#withdraw"
    resource :customers, only:[:show, :edit, :update]
    resources :items, only:[:index, :show]
    resources :cart_items, except:[:show, :new, :edit]
    delete "/cart_items", to: "cart_items#destroy_all"
    resources :orders, except:[:edit, :update, :destroy] do
      collection do
        get "complete"
        post "confirm"
      end
    end
    resources :deliveries, except:[:new, :show]

    get '/genre_search', to: "searches#genre_search"
    get '/item_search', to: "searches#item_search"
   end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def sum_of_price
    item.add_tax_included_price * quantity
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items  , dependent: :destroy
  has_many :orders         , dependent: :destroy
  has_many :deliveries     , dependent: :destroy

  def full_name
   last_name + " " + first_name
  end

  def full_name_kana
    last_name_kana + " " + first_name_kana
  end

  def full_name_no_blanks
    last_name + first_name
  end

  def full_address
    "〒" + self.postal_code + "  " + self.address + last_name + " " + first_name
  end

  def cart_items_total_price
    sum = 0
    self.cart_items.each { |cart_item| sum += cart_item.sum_of_price }
    return sum
  end
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer
  
  def full_addresses
    "〒" + self.postal_code + "  " + self.address + "  " + self.name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  attachment :image
  
  validates :name, presence: true
  validates :image, presence: true
  validates :detail, presence: true
  validates :tax_excluded_price, presence: true
  validates :is_active, inclusion: [true, false]
  
  def add_tax_included_price
    (self.tax_excluded_price * 1.10).round
  end
  
  def self.search(search)
    if search != ""
      Item.where('name LIKE ?', "%#{search}%")
    else
      Item.all
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  after_update :check_order_detail

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum status: {
      wating_for_payment: 0,
      confirmed_payment: 1,
      making: 2,
      ready_to_ship: 3,
      sent: 4
   }

   enum payment_method: {
      credit_card: 0,
      transfer: 1
   }


  def set_receiver(receiver)
    self.address = receiver.address
    self.postal_code = receiver.postal_code
    if receiver.is_a?(Customer)
      self.name = receiver.full_name.gsub(" ", "")
    else
      self.name = receiver.name
    end
  end

  def order_items_total_price
    (total_price - 800).round
  end

  def order_items_total_quantity
    self.order_items.sum(:quantity)
  end


  after_create :move_cart_items
  after_update :check_order_detail

  private

  def move_cart_items
    cart_items_list = self.customer.cart_items.map do |cart_item|
      {
        item_id: cart_item.item_id,
        tax_included_price: cart_item.item.add_tax_included_price,
        quantity: cart_item.quantity
      }
    end
    self.order_details.create(cart_items_list)
    self.customer.cart_items.destroy_all
  end

  def check_order_detail
    if self.status == "confirmed_payment"
      self.order_details.update_all(making_status: "wating_for_make")
    end
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  after_update :check_making_status
  
  belongs_to :item
  belongs_to :order
  
  enum making_status: { not_startable: 0,  wating_for_make: 1, making: 2, completed: 3 }

  def sum_of_price
    (self.tax_included_price * self.quantity).round
  end

  private

  def check_making_status
    if self.making_status == "making"
      self.order.update(status: "making")
    elsif self.making_status == "completed"
      if self.order.order_details.all? { |order_detail| order_detail.making_status == "completed" }
        self.order.update(status: "ready_to_ship")
      end
    end
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  layout "admin"
  
  def index
    @genres=Genre.all
    @genre=Genre.new
  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def create
    @genre=Genre.new(genre_params)
    @genre=Genre.all
    if @genre.save
      redirect_to admins_genres_path
    else
      render :index
    end
  end

  def update
    @genre=Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admins_genres_path
    else
      render :edit
    end
  end
  
  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  layout "admin"

  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  layout "admin"

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admins_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_item_path(@item)
    else
      render :edit
    end
  end

  private
    def item_params
      params.require(:item).permit(:genre_id, :name, :detail, :image, :tax_excluded_price, :is_active)
    end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  layout "admin"
  
  def index
    if params[:customer_id]
     @orders = Order.where(customer_id: params[:customer_id])
    else
     @orders = Order.all
    end
  end

  def show
    @order = Order.find(params[:id])
    @order.postage = 800
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      flash[:notice] = "注文ステータスの更新に成功しました"
    end
    redirect_to admins_order_path(@order)
  end
  
  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<h2 class="offset-1 mt-4">ジャンル編集</h2>

<div class="col-8 mt-5">
  <%= form_with model: @genre, url: admin_genre_path, local: true do |f| %>
  <div class="form-group row">
    <div class="col-2"><%= f.label :ジャンル名 %></div>
    <div class="col-4"><%= f.text_field :name %></div>
    <div class="col-3"><%= f.submit "保存", class: "btn btn-success" %></div>
  </div>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<h2 class="offset-1 mt-4">ジャンル一覧・追加</h2>

<div class="col-8 mt-5">
  <%= form_with model: @genre, url: admin_genres_path, local: true do |f| %>
   <div class="form-group row">
     <div class="col-2"><%= f.label :ジャンル名 %></div>
     <div class="col-4"><%= f.text_field :name, placeholder: "ジャンル名" %></div>
     <div class="col-3"><%= f.submit "新規登録", class: "btn btn-success" %></div>
   </div>
  <% end %>
</div>

<div class="row mt-5">
  <div class="col-5">
    <table>
      <thead>
        <tr>
          <th>ジャンル</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td><%= link_to "編集", edit_admin_genre_path(genre), class: "btn btn-success" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/homes/top.html.erb
<%= render 'admin/orders/index', orders: @orders %>

app/views/admin/items/_index.html.erb
<div class="row offset-1 col-10 mt-3">
  <table>
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜き価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item.id) %></td>
        <td><%= item.tax_excluded_price.to_s(:delimited) %></td>
        <td><%= item.genre.name %></td>
        <% if item.is_active? %>
         <td class="text-success"><strong>販売中</strong></td>
        <% else %>
         <td class="text-secondary"><strong>販売停止中</strong></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/items/edit.html.erb
<h2 class="offset-1">商品編集</h2>

<div class="col-8 offset-2 mt-5">
  <%= form_with model: @item, url: admin_item_path, local: true do |f| %>
  <div class="form-group row">
    <div class="col-4"><%= f.label :商品画像 %></div>
    <div class="col-8"><%= f.attachment_field :image %></div>
  </div>
  
  <div class="form-group row">
    <div class="col-4"><%= f.label :商品名 %></div>
    <div class="col-8"><%= f.text_field :name, class: "form-control" %></div>
  </div>
  
  <div class="form-group row">
      <div class="col-4"><%= f.label :商品説明 %></div>
      <div class="col-8"><%= f.text_area :detail, class: "form-control", rows: "6" %></div>
    </div>

    <div class="form-group row">
      <div class="col-4"><%= f.label :ジャンル %></div>
      <div class="col-8"><%= f.collection_select(:genre_id, Genre.all, :id, :name, {include_blank: "--選択してください--"}, {class: "form-control"}) %></div>
    </div>

    <div class="form-group row">
      <div class="col-4"><%= f.label :税抜価格 %></div>
      <div class="col-8 d-flex flex-row"><%= f.text_field :tax_excluded_price, class: "form-control" %>円</div>
    </div>

    <div class="form-group row">
      <div class="col-4"><%= f.label :販売ステータス %></div>
      <div class="col-8">
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active, "販売中" %>
        <%= f.radio_button :is_active, :false, class: "ml-3" %>
        <%= f.label :is_active, "販売停止中" %>
      </div>
    </div>

    <div class="text-center mt-4">
      <%= f.submit "変更を保存", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="row offset-2">
  <h2>商品一覧</h2>

  <div class="offset-6 col-4">
    <%= link_to new_admin_item_path, class: "btn btn-light" do %>
    <i class="fas fa-ad"></i>
    <% end %>
  </div>
</div>

<%= render "index", items: @items %>

app/views/admin/items/new.html.erb
<h3 class="offset-1">商品新規登録</h3>

<div class="col-8 offset-2 mt-5">
  <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
    <div class="form-group row">
      <div class="col-4"><%= f.label :商品画像 %></div>
      <div class="col-8"><%= f.attachment_field :image %></div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :商品名 %></div>
      <div class="col-8"><%= f.text_field :name, placeholder: "商品名", class: "form-control" %></div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :商品説明 %></div>
      <div class="col-8"><%= f.text_area :detail, placeholder: "ここに説明文を記述します", class: "form-control", rows: "6" %></div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :ジャンル %></div>
      <div class="col-8"><%= f.collection_select(:genre_id, Genre.all, :id, :name, {include_blank: "--選択してください--"}, {class: 'form-control'}) %></div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :税抜価格 %></div>
      <div class="col-8 d-flex flex-row"><%= f.text_field :tax_excluded_price, placeholder: "1000", class: "form-control" %>
        <div class="mt-2">円</div>
      </div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :販売ステータス %></div>
      <div class="col-8">
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active, "販売中" %>
        <%= f.radio_button :is_active, :false, class: "ml-3" %>
        <%= f.label :is_active, "販売停止中" %>
      </div>
    </div>

    <div class="text-center mt-4">
      <%= f.submit "新規登録", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<h3 class="offset-1">商品詳細</h3>

<div class="row offset-1 mt-5">
  <div class="col-lg-7">

    <div class="row">
      <div class="col-5">商品名</div>
      <div class="col-7"><%= @item.name %></div>
    </div>

    <div class="row mt-3">
      <div class="col-5">商品説明</div>
      <div class="col-7"><%= @item.detail %></div>
    </div>

    <div class="row mt-3">
      <div class="col-5">ジャンル</div>
      <div class="col-7"><%= @item.genre.name %></div>
    </div>

    <div class="row mt-3">
      <div class="col-5">税込価格<br>(税抜価格)</div>
      <div class="col-7"><%= @item.add_tax_included_price.to_s(:delimited) %>（<%= @item.tax_excluded_price.to_s(:delimited)%>）円</div>
    </div>

    <div class="row mt-3">
      <div class="col-5">販売ステータス</div>
      <div class="col-7">
        <% if @item.is_active? %>
          <div class="text-success"><strong>販売中</strong></div>
        <% else %>
          <div class="text-secondary"><strong>販売停止中</strong></div>
        <% end %>
      </div>
    </div>

    <div class="text-center mt-4">
      <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
    </div>

  </div>
</div>

app/views/admin/orders/_index.html.erb
<h3 class="mb-4">注文履歴一覧</h3>

<table>
  <thead>
    <tr>
      <th>購入日時</th>
      <th>購入者</th>
      <th>注文個数</th>
      <th>注文ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% orders.each do |order| %>
      <tr>
        <td><%= link_to order.created_at.strftime("%Y/%m/%d %H:%M:%S"), admin_order_path(order), class:"text-dark", style: "text-decoration:underline;" %></td>
        <td><%= order.customer.full_name %></td>
        <td><%= order.order_details.sum(:quantity) %></td>
        <td><%= order.status_i18n %></td>
      </tr>
    <% end %>
  </tbody>
  </table>

app/views/admin/orders/index.html.erb
<%= render 'index', orders: @orders %>

app/views/admin/orders/show.html.erb
<h3 class="mb-4">注文履歴詳細</h3>

 <table class="table table-borderless">
    <tr>
      <td>購入者</td>
      <td><%= link_to @order.customer.full_name, admin_customer_path(@order.customer) %></td>
      <td></td>
    </tr>
    <tr>
      <td>注文日</td>
      <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
      <td></td>
    </tr>
    <tr>
      <td>配送先</td>
      <td>
        <div>〒 <%= @order.postal_code %> <%= @order.address %></div>
        <div><%= @order.name %></div>
      </td>
      <td></td>
    </tr>
    <tr>
      <td>支払方法</td>
      <td><%= @order.payment_method_i18n %></td>
      <td></td>
    </tr>
    <tr>
      <td class="col-md-3">注文ステータス</td>
      <%= form_with model:[:admin, @order], local: true do |f| %>
        <td>
          <div class="form-inline">
            <%= f.collection_select(:status, Order.statuses_i18n, :first, :last, {selected: @order.status}, {class: "form-control"}) %>
            <%= f.submit "更新", class:"btn btn-success ml-3" %>
          </div>
        </td>
        <td></td>
      <% end %>
    </tr>
  </table>
  <div class="row mt-5">
    <div class="col-md-9">
      <table class="table table-light table-striped">
        <thead>
          <tr class="text-white bg-dark">
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_details| %>
            <tr>
              <td><%= order_details.product.name %></td>
              <td><%= order_details.tax_included_price %></td>
              <td><%= order_details.quantity %></td>
              <td><%= order_details.sum_of_price %></td>
              <%= form_with model:[:admin, order_details], local: true do |f| %>
                <td><%= f.collection_select(:making_status, OrderDetail.making_statuses_i18n, :first, :last,  { selected: order_details.making_status }, {class: "form-control"})%></td>
                <td><%= f.submit "更新",  class:"btn btn-success" %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-3 d-flex align-items-end">
      <table class="table table-borderless">
        <tr>
          <td class="font-weight-bold">商品合計</td>
          <td><%= @order.order_items_total_price%></td>
        </tr>
        <tr>
          <td class="font-weight-bold">送料</td>
          <td><%= @order.postage %></td>
        </tr>
        <tr>
          <td class="font-weight-bold">請求金額合計</td>
          <td><%= @order.order_items_total_price + @order.postage %></td>
        </tr>
      </table>
    </div>
  </div>