config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip:[:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    root to: 'homes#top'
    resources :items, expect:[:destroy]
    resources :genres, only:[:index, :edit, :create, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
  end

  root to: "public/homes#top"

  devise_for :customer, skip:[:passwords], controllers:{
    registrations: "customer/registrations",
    sessions: "customer/sessions"
  }

  scope module: :public do
    get "/about", to: "homes#about"
    get "/customers/unsubscribe", to: "customers#unsubscribe"
    patch "/customers/withdraw", to: "customers#withdraw"
    resource :customers, only:[:show, :edit, :update]
    resources :items, only:[:index, :show]
    resources :cart_items, except:[:show, :new, :edit]
    delete "/cart_items", to: "cart_items#destroy_all"
    resources :orders, except:[:edit, :update, :destroy] do
      collection do
        get "complete"
        post "confirm"
      end
    end
    resources :deliveries, except:[:new, :show]

    get '/genre_search', to: "searches#genre_search"
    get '/item_search', to: "searches#item_search"
   end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def sum_of_price
    item.add_tax_included_price * quantity
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items  , dependent: :destroy
  has_many :orders         , dependent: :destroy
  has_many :deliveries     , dependent: :destroy

  def full_name
   last_name + " " + first_name
  end

  def full_name_kana
    last_name_kana + " " + first_name_kana
  end

  def full_name_no_blanks
    last_name + first_name
  end

  def full_address
    "〒" + self.postal_code + "  " + self.address + last_name + " " + first_name
  end

  def cart_items_total_price
    sum = 0
    self.cart_items.each { |cart_item| sum += cart_item.sum_of_price }
    return sum
  end
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer
  
  def full_addresses
    "〒" + self.postal_code + "  " + self.address + "  " + self.name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  attachment :image
  
  validates :name, presence: true
  validates :image, presence: true
  validates :detail, presence: true
  validates :tax_excluded_price, presence: true
  validates :is_active, inclusion: [true, false]
  
  def add_tax_included_price
    (self.tax_excluded_price * 1.10).round
  end
  
  def self.search(search)
    if search != ""
      Item.where('name LIKE ?', "%#{search}%")
    else
      Item.all
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  after_update :check_order_detail

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum status: {
      wating_for_payment: 0,
      confirmed_payment: 1,
      making: 2,
      ready_to_ship: 3,
      sent: 4
   }

   enum payment_method: {
      credit_card: 0,
      transfer: 1
   }


  def set_receiver(receiver)
    self.address = receiver.address
    self.postal_code = receiver.postal_code
    if receiver.is_a?(Customer)
      self.name = receiver.full_name.gsub(" ", "")
    else
      self.name = receiver.name
    end
  end

  def order_items_total_price
    (total_price - 800).round
  end

  def order_items_total_quantity
    self.order_items.sum(:quantity)
  end


  after_create :move_cart_items
  after_update :check_order_detail

  private

  def move_cart_items
    cart_items_list = self.customer.cart_items.map do |cart_item|
      {
        item_id: cart_item.item_id,
        tax_included_price: cart_item.item.add_tax_included_price,
        quantity: cart_item.quantity
      }
    end
    self.order_details.create(cart_items_list)
    self.customer.cart_items.destroy_all
  end

  def check_order_detail
    if self.status == "confirmed_payment"
      self.order_details.update_all(making_status: "wating_for_make")
    end
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  after_update :check_making_status
  
  belongs_to :item
  belongs_to :order
  
  enum making_status: { not_startable: 0,  wating_for_make: 1, making: 2, completed: 3 }

  def sum_of_price
    (self.tax_included_price * self.quantity).round
  end

  private

  def check_making_status
    if self.making_status == "making"
      self.order.update(status: "making")
    elsif self.making_status == "completed"
      if self.order.order_details.all? { |order_detail| order_detail.making_status == "completed" }
        self.order.update(status: "ready_to_ship")
      end
    end
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  layout "admin"

  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  layout "admin"

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admins_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_item_path(@item)
    else
      render :edit
    end
  end

  private
    def item_params
      params.require(:item).permit(:genre_id, :name, :detail, :image, :tax_excluded_price, :is_active)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <div><%= link_to "Admin", admin_root_path %></div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
               <li>
                 <%= link_to "商品一覧", admin_items_path, class:"fas fa-cookie-bite nav-link text-light" %>
               </li>
               <li>
                 <%= link_to "会員一覧", admin_customers_path, class:"fas fa-users nav-link text-light" %>
               </li>
               <li>
                 <%= link_to "注文履歴一覧", admin_root_path, class:"fas fa-shopping-cart nav-link text-light" %>
               </li>
               <li>
                 <%= link_to "ジャンル一覧", admin_genres_path, class:"fas fa-list-alt nav-link text-light" %>
               </li>
               <li>
                 <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light" %>
               </li>
               <% else %>
               <li>
                  <%= link_to "About", about_path, class:"fas fa-birthday-cake nav-link text-light" %>
               </li>
               <li>
                 <%= link_to "商品一覧", items_path, class:"fas fa-link nav-link text-light" %>
               </li>
               <li>
                 <%= link_to "新規登録", new_customer_registration_path, class:"fas fa-user-plus nav-link text-light" %>
               </li>
               <li>
                 <%= link_to "ログイン", new_customer_session_path, class:"fas fa-sign-in-alt nav-link text-light" %>
               </li>
               <% end %>
            </ul>
            <ul class="navbar-nav mt-1">
              <li class="ml-auto">
                <%= render "public/searches/form" %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main style="margin-bottom:80px">
      <div class="container p-3">
        <p class="text-success"><%= notice %></p>
        <p class="text-danger"><%= alert %></p>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container">
        <div><%= link_to "ながのCAKE", root_path %></div>

          <% if customer_signed_in? %>
            <p class="p-3 m-0 text-light">ようこそ、<%= current_customer.last_name %>さん！</p>
          <% end %>

          <button class="navbar-toggler menu-trigger" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <li>
                  <%= link_to "マイページ", customers_path, class:"fas fa-user nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "商品一覧", items_path, class:"fas fa-list nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "カート", cart_items_path, class:"fas fa-cart-plus nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light" %>
                </li>
              <% else %>
                <li>
                  <%= link_to "About", about_path, class:"fas fa-birthday-cake nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "商品一覧", items_path, class:"fas fa-list nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "新規登録", new_customer_registration_path, class:"fas fa-user-plus nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "ログイン", new_customer_session_path, class:"fas fa-sign-in-alt nav-link text-light" %>
                </li>
              <% end %>
            </ul>

            <div>
              <%= render "public/searches/form" %>
            </div>
          </div>

        </div>
      </nav>
    </header>

    <main style="margin-bottom:80px">
      <div class="container p-3">
        <p class="text-success"><%= notice %></p>
        <p class="text-danger"><%= alert %></p>
        <%= yield %>
      </div>
    </main>

    <footer>
    </footer>

  </body>
</html>